# Generated by Django 5.2.6 on 2025-10-01 13:25

import profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=profile.models.user_profile_image_path, verbose_name='Profile Image'),
        ),
    ]
